project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://eringrand.github.io # you must change this appropriately for RSS feeds to work properly
  title: "Erin Grand"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/eringrand
      - icon: twitter
        href: https://twitter.com/astroeringrand
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    
execute:
  freeze: auto

